<?php
/**
 * @file
 * fish_vocab_lake.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function fish_vocab_lake_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Beaver Tailwater',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '072b3221-cc7f-40be-9169-2cec5c76d97a',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Sequoyah',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '216c145f-7dc0-4bd5-aecc-ae6b492bc4b5',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Norrell',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '21ad59a5-7221-4d5d-85d7-84d66820b7a0',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.254167 33.851268)',
          'geo_type' => 'point',
          'lat' => '33.851268000000',
          'lon' => '-92.254167000000',
          'left' => '-92.254167000000',
          'top' => '33.851268000000',
          'right' => '-92.254167000000',
          'bottom' => '33.851268000000',
          'geohash' => '9yn2sdqtfjer',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Bear Creek Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22d69856-59cc-4369-8a11-6cb62aa34050',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-90.696865 34.708942)',
          'geo_type' => 'point',
          'lat' => '34.708942000000',
          'lon' => '-90.696865000000',
          'left' => '-90.696865000000',
          'top' => '34.708942000000',
          'right' => '-90.696865000000',
          'bottom' => '34.708942000000',
          'geohash' => '9ypt2nsd1zez',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Elmdale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2497a545-5195-4e84-8df6-2a2aedbae9d8',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Beaver Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24f8feeb-7d6e-482c-be72-79d32af0de37',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.9235 36.348)',
          'geo_type' => 'point',
          'lat' => '36.348000000000',
          'lon' => '-93.923500000000',
          'left' => '-93.923500000000',
          'top' => '36.348000000000',
          'right' => '-93.923500000000',
          'bottom' => '36.348000000000',
          'geohash' => '9ymny8yyr',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Fayetteville',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29c1dc5c-1c95-4ffb-aed9-512213dd7043',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-94.130819 36.136638)',
          'geo_type' => 'point',
          'lat' => '36.136638000000',
          'lon' => '-94.130819000000',
          'left' => '-94.130819000000',
          'top' => '36.136638000000',
          'right' => '-94.130819000000',
          'bottom' => '36.136638000000',
          'geohash' => '9ymjd42p0vw4',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Norfork',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '316c4247-9784-4eda-9596-0f5d5f498259',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.2309 36.3494)',
          'geo_type' => 'point',
          'lat' => '36.349400000000',
          'lon' => '-92.230900000000',
          'left' => '-92.230900000000',
          'top' => '36.349400000000',
          'right' => '-92.230900000000',
          'bottom' => '36.349400000000',
          'geohash' => '9yqqv1pw8',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Horseshoe Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '37ddca37-67ce-4c14-9212-54782d816b4f',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Clear Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3951bcff-212f-4aad-ac5f-0c95ba759761',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.002564 34.11413)',
          'geo_type' => 'point',
          'lat' => '34.114130000000',
          'lon' => '-93.002564000000',
          'left' => '-93.002564000000',
          'top' => '34.114130000000',
          'right' => '-93.002564000000',
          'bottom' => '34.114130000000',
          'geohash' => '9yjf5dm95ny0',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Maumelle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a30be3a-f308-4ec9-90db-84df460df16a',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Saline River Access in Benton',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3fbc9b85-3ec4-4dbc-85ef-61b7c46fb979',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.254167 33.851268)',
          'geo_type' => 'point',
          'lat' => '33.851268000000',
          'lon' => '-92.254167000000',
          'left' => '-92.254167000000',
          'top' => '33.851268000000',
          'right' => '-92.254167000000',
          'bottom' => '33.851268000000',
          'geohash' => '9yn2sdqtfjer',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Peckerwood Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '425d5b19-3066-4757-b864-4133373b0556',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'White River',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '47863758-4af1-4f6c-bc34-4fe7a4ee2157',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Mississippi River Oxbows',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '49b039e9-06ed-4e13-ac64-dc7bd678212b',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Chicot',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a9338b8-7238-401e-8752-9c2f5c3da3aa',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-91.240305 33.317908)',
          'geo_type' => 'point',
          'lat' => '33.317908000000',
          'lon' => '-91.240305000000',
          'left' => '-91.240305000000',
          'top' => '33.317908000000',
          'right' => '-91.240305000000',
          'bottom' => '33.317908000000',
          'geohash' => '9vzjec2ffu1w',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Catherine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '51248504-1771-4f14-9e81-b3f998631720',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.94462 34.444806)',
          'geo_type' => 'point',
          'lat' => '34.444806000000',
          'lon' => '-92.944620000000',
          'left' => '-92.944620000000',
          'top' => '34.444806000000',
          'right' => '-92.944620000000',
          'bottom' => '34.444806000000',
          'geohash' => '9yjguyrz93hp',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Pickthorne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5260b578-8956-4603-93f0-bfe2eaf7c504',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.066667 34.916667)',
          'geo_type' => 'point',
          'lat' => '34.916667000000',
          'lon' => '-92.066667000000',
          'left' => '-92.066667000000',
          'top' => '34.916667000000',
          'right' => '-92.066667000000',
          'bottom' => '34.916667000000',
          'geohash' => '9ynw8urh74mr',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Dardanelle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54d6b685-edf9-4551-ad7c-30d3408af61a',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Spring River',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5c711375-c910-4791-be99-787ef9b16e1f',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-91.37935 36.298228)',
          'geo_type' => 'point',
          'lat' => '36.298228000000',
          'lon' => '-91.379350000000',
          'left' => '-91.379350000000',
          'top' => '36.298228000000',
          'right' => '-91.379350000000',
          'bottom' => '36.298228000000',
          'geohash' => '9yrn2xgsdb4h',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Brewer Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '610a4775-88b3-4741-af82-ac02c6a9c76f',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.591667 35.241667)',
          'geo_type' => 'point',
          'lat' => '35.241667000000',
          'lon' => '-92.591667000000',
          'left' => '-92.591667000000',
          'top' => '35.241667000000',
          'right' => '-92.591667000000',
          'bottom' => '35.241667000000',
          'geohash' => '9yq0mp8c9fch',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Craig D. Campbell Lake Conway Reservoir',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '61d35359-30c9-4001-8e8d-a305c5e62df7',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Crown Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '620785e6-ffb0-4013-80e0-91fb07416d00',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-91.733443 36.205207)',
          'geo_type' => 'point',
          'lat' => '36.205207000000',
          'lon' => '-91.733443000000',
          'left' => '-91.733443000000',
          'top' => '36.205207000000',
          'right' => '-91.733443000000',
          'bottom' => '36.205207000000',
          'geohash' => '9yqvbwcwxgg0',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Overcup',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '62cece23-6236-43a3-9d10-0e5293e20afb',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.716667 35.2)',
          'geo_type' => 'point',
          'lat' => '35.200000000000',
          'lon' => '-92.716667000000',
          'left' => '-92.716667000000',
          'top' => '35.200000000000',
          'right' => '-92.716667000000',
          'bottom' => '35.200000000000',
          'geohash' => '9yq04pvyc5d6',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Willastein in Maumelle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '63d75fd1-2a1b-4c71-bddb-c8e23e931461',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Bishop Park Lakes in Bryant',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '660b3929-4919-4d7b-98de-ece37f672f9d',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.254167 33.851268)',
          'geo_type' => 'point',
          'lat' => '33.851268000000',
          'lon' => '-92.254167000000',
          'left' => '-92.254167000000',
          'top' => '33.851268000000',
          'right' => '-92.254167000000',
          'bottom' => '33.851268000000',
          'geohash' => '9yn2sdqtfjer',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Greeson Tailwater (Little Missouri River)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '675ade3c-1206-4777-bbc1-2f04f11553cf',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.368199 33.932097)',
          'geo_type' => 'point',
          'lat' => '33.932097000000',
          'lon' => '-93.368199000000',
          'left' => '-93.368199000000',
          'top' => '33.932097000000',
          'right' => '-93.368199000000',
          'bottom' => '33.932097000000',
          'geohash' => '9yj9535kg32f',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Greeson',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '67f966b2-c7dd-41f0-86d2-951c036015b9',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.7309 34.2092)',
          'geo_type' => 'point',
          'lat' => '34.209200000000',
          'lon' => '-93.730900000000',
          'left' => '-93.730900000000',
          'top' => '34.209200000000',
          'right' => '-93.730900000000',
          'bottom' => '34.209200000000',
          'geohash' => '9yj6e5e5p',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Bailey (Petit Jean Mountain)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a07b079-6369-4e43-8168-cf8753e07df6',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.918158 35.129675)',
          'geo_type' => 'point',
          'lat' => '35.129675000000',
          'lon' => '-92.918158000000',
          'left' => '-92.918158000000',
          'top' => '35.129675000000',
          'right' => '-92.918158000000',
          'bottom' => '35.129675000000',
          'geohash' => '9yjzve5j1yp9',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Greers Ferry',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ae11b13-c701-47ca-b621-cd391bff5075',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.1197 35.5205)',
          'geo_type' => 'point',
          'lat' => '35.520500000000',
          'lon' => '-92.119700000000',
          'left' => '-92.119700000000',
          'top' => '35.520500000000',
          'right' => '-92.119700000000',
          'bottom' => '35.520500000000',
          'geohash' => '9yq6pf23z',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Crystal Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6af6bd57-393e-432a-83a0-f7f876910a23',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-94.439456 36.340459)',
          'geo_type' => 'point',
          'lat' => '36.340459000000',
          'lon' => '-94.439456000000',
          'left' => '-94.439456000000',
          'top' => '36.340459000000',
          'right' => '-94.439456000000',
          'bottom' => '36.340459000000',
          'geohash' => '9ykydzx690t9',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Wapanocca Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ee8bff7-abae-4098-97cc-8bbd2fbbc050',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Buffalo River',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6f15e78e-18fd-4ef1-a459-f870b631182e',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.819043 36.036352)',
          'geo_type' => 'point',
          'lat' => '36.036352000000',
          'lon' => '-92.819043000000',
          'left' => '-92.819043000000',
          'top' => '36.036352000000',
          'right' => '-92.819043000000',
          'bottom' => '36.036352000000',
          'geohash' => '9ymvpb5nzwch',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Arkansas River at Morrilton',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7020a6e8-0262-4c79-a2bd-c2a03ac155b4',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Nimrod',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7688a975-ea9b-4c39-b4ea-b674bdfcd4af',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.20681 34.95363)',
          'geo_type' => 'point',
          'lat' => '34.953630000000',
          'lon' => '-93.206810000000',
          'left' => '-93.206810000000',
          'top' => '34.953630000000',
          'right' => '-93.206810000000',
          'bottom' => '34.953630000000',
          'geohash' => '9yjwz50geu',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Blue Mountain Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c6fb8a8-46f2-4e59-a714-65dd741630b1',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.68497 35.10643)',
          'geo_type' => 'point',
          'lat' => '35.106430000000',
          'lon' => '-93.684970000000',
          'left' => '-93.684970000000',
          'top' => '35.106430000000',
          'right' => '-93.684970000000',
          'bottom' => '35.106430000000',
          'geohash' => '9yjrsnutvb',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Harris Brake Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8772bde7-53ea-405d-a0df-a0360f65eef3',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.766667 34.983333)',
          'geo_type' => 'point',
          'lat' => '34.983333000000',
          'lon' => '-92.766667000000',
          'left' => '-92.766667000000',
          'top' => '34.983333000000',
          'right' => '-92.766667000000',
          'bottom' => '34.983333000000',
          'geohash' => '9ynp1092evzt',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Valencia in Maumelle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '87d1d18d-2adf-4d02-a03e-be05fcdcdfb8',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Little Red River (Greers Ferry Tailwater)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a658109-d868-4955-8359-4f228aaed969',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-91.721443 35.341859)',
          'geo_type' => 'point',
          'lat' => '35.341859000000',
          'lon' => '-91.721443000000',
          'left' => '-91.721443000000',
          'top' => '35.341859000000',
          'right' => '-91.721443000000',
          'bottom' => '35.341859000000',
          'geohash' => '9yqc0cf3r2p0',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Sunset Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8adb2ed3-632d-4951-bda2-714f4bad2257',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Arkansas River (Little Rock Pool)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8fe72dc2-cec1-4b23-a75d-a43c22f0ae62',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Ouachita',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92cc8cf4-f9a8-4d3b-a1be-31778592f34c',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.3319 34.5993)',
          'geo_type' => 'point',
          'lat' => '34.599300000000',
          'lon' => '-93.331900000000',
          'left' => '-93.331900000000',
          'top' => '34.599300000000',
          'right' => '-93.331900000000',
          'bottom' => '34.599300000000',
          'geohash' => '9yjsu4tg9',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Little Maumelle River',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '99ee30d0-1778-45f6-ac74-cf95c2288d4f',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Cane Creek Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9c08498a-ed02-4d45-8090-905a87db8514',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-91.770632 33.930251)',
          'geo_type' => 'point',
          'lat' => '33.930251000000',
          'lon' => '-91.770632000000',
          'left' => '-91.770632000000',
          'top' => '33.930251000000',
          'right' => '-91.770632000000',
          'bottom' => '33.930251000000',
          'geohash' => '9yn9p8ydj31p',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Bull Shoals',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9c50ba1d-cfd2-4270-81e4-2edf9b0b0828',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.7706 36.4997)',
          'geo_type' => 'point',
          'lat' => '36.499700000000',
          'lon' => '-92.770600000000',
          'left' => '-92.770600000000',
          'top' => '36.499700000000',
          'right' => '-92.770600000000',
          'bottom' => '36.499700000000',
          'geohash' => '9yqp8uwd0',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake SWEPCO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a42ca6ce-b713-44ae-ab3d-9efdad31b961',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-94.534 36.251387)',
          'geo_type' => 'point',
          'lat' => '36.251387000000',
          'lon' => '-94.534000000000',
          'left' => '-94.534000000000',
          'top' => '36.251387000000',
          'right' => '-94.534000000000',
          'bottom' => '36.251387000000',
          'geohash' => '9yky0z67whkd',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Maddox Bay',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b057e260-1686-4dca-b0e7-f758df94d5cc',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Frierson',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3433f02-7c18-453f-8a5a-6feec7651b73',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-90.716667 35.966667)',
          'geo_type' => 'point',
          'lat' => '35.966667000000',
          'lon' => '-90.716667000000',
          'left' => '-90.716667000000',
          'top' => '35.966667000000',
          'right' => '-90.716667000000',
          'bottom' => '35.966667000000',
          'geohash' => '9yrkxew1h2wm',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Millwood Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b45b5a59-3ce7-4248-8842-ceae11f18c93',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.9771 33.7432)',
          'geo_type' => 'point',
          'lat' => '33.743200000000',
          'lon' => '-93.977100000000',
          'left' => '-93.977100000000',
          'top' => '33.743200000000',
          'right' => '-93.977100000000',
          'bottom' => '33.743200000000',
          'geohash' => '9vvpvqzbq',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'White Oak Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b4e10a1f-72de-44a0-a22a-46241ef2456d',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.366667 33.775)',
          'geo_type' => 'point',
          'lat' => '33.775000000000',
          'lon' => '-92.366667000000',
          'left' => '-92.366667000000',
          'top' => '33.775000000000',
          'right' => '-92.366667000000',
          'bottom' => '33.775000000000',
          'geohash' => '9yn24hs9ssm4',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Fourche La Fave River',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b7aeaae7-048f-4b27-89db-d39b6b89504e',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.318667 34.922533)',
          'geo_type' => 'point',
          'lat' => '34.922533000000',
          'lon' => '-93.318667000000',
          'left' => '-93.318667000000',
          'top' => '34.922533000000',
          'right' => '-93.318667000000',
          'bottom' => '34.922533000000',
          'geohash' => '9yjwsmrqmryx',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Benton City Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'baec9bba-03ff-4290-a92a-81aac6ec17eb',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.403168 34.86254)',
          'geo_type' => 'point',
          'lat' => '34.862540000000',
          'lon' => '-92.403168000000',
          'left' => '-92.403168000000',
          'top' => '34.862540000000',
          'right' => '-92.403168000000',
          'bottom' => '34.862540000000',
          'geohash' => '9ynq36d140kp',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Ouachita River Oxbows',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c06d1225-cdf5-4786-9ae9-85975dc5aba3',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.742851 33.69935)',
          'geo_type' => 'point',
          'lat' => '33.699350000000',
          'lon' => '-92.742851000000',
          'left' => '-92.742851000000',
          'top' => '33.699350000000',
          'right' => '-92.742851000000',
          'bottom' => '33.699350000000',
          'geohash' => '9vyp9wf8yynh',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Crooked Creek',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c1bafbca-f6ae-48fa-aafc-b132a9819816',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.764187 36.23556)',
          'geo_type' => 'point',
          'lat' => '36.235560000000',
          'lon' => '-92.764187000000',
          'left' => '-92.764187000000',
          'top' => '36.235560000000',
          'right' => '-92.764187000000',
          'bottom' => '36.235560000000',
          'geohash' => '9yqn1h7pmvby',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Winona',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c5834e7e-c07c-45e3-8960-2f094931074a',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.254167 33.851268)',
          'geo_type' => 'point',
          'lat' => '33.851268000000',
          'lon' => '-92.254167000000',
          'left' => '-92.254167000000',
          'top' => '33.851268000000',
          'right' => '-92.254167000000',
          'bottom' => '33.851268000000',
          'geohash' => '9yn2sdqtfjer',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'White River (Bull Shoals Tailwater)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c5aa6b06-e738-4654-9583-df6adccede2c',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Hamilton',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc27c851-7abc-4430-a611-7488d394a243',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.102562 34.451849)',
          'geo_type' => 'point',
          'lat' => '34.451849000000',
          'lon' => '-93.102562000000',
          'left' => '-93.102562000000',
          'top' => '34.451849000000',
          'right' => '-93.102562000000',
          'bottom' => '34.451849000000',
          'geohash' => '9yjgcrub944h',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Tri-County Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e3aa90c1-9d18-47ee-ada3-bded6ea029fa',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.366667 33.775)',
          'geo_type' => 'point',
          'lat' => '33.775000000000',
          'lon' => '-92.366667000000',
          'left' => '-92.366667000000',
          'top' => '33.775000000000',
          'right' => '-92.366667000000',
          'bottom' => '33.775000000000',
          'geohash' => '9yn24hs9ssm4',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'DeGray Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5066d62-0d83-4d0e-bb8a-9a8b7158df41',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-93.1919 34.2391)',
          'geo_type' => 'point',
          'lat' => '34.239100000000',
          'lon' => '-93.191900000000',
          'left' => '-93.191900000000',
          'top' => '34.239100000000',
          'right' => '-93.191900000000',
          'bottom' => '34.239100000000',
          'geohash' => '9yjdz359p',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Prairie Grove Lake',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e632b8e4-82e6-4cc6-98d7-014caefd20b2',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'North Fork River (Norfork Tailwater)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ea69dcd8-b066-4084-9231-9ebff9486224',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-92.245481 36.246239)',
          'geo_type' => 'point',
          'lat' => '36.246239000000',
          'lon' => '-92.245481000000',
          'left' => '-92.245481000000',
          'top' => '36.246239000000',
          'right' => '-92.245481000000',
          'bottom' => '36.246239000000',
          'geohash' => '9yqqhykvss8j',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lake Poinsett',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f8a9dad9-de89-4604-bd3d-beb6840968b6',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => 'POINT (-90.675 35.525)',
          'geo_type' => 'point',
          'lat' => '35.525000000000',
          'lon' => '-90.675000000000',
          'left' => '-90.675000000000',
          'top' => '35.525000000000',
          'right' => '-90.675000000000',
          'bottom' => '35.525000000000',
          'geohash' => '9yrd0ehk',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Arkansas River (Maumelle Pool)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa70f319-2bfe-42f2-afed-0a2deba24e20',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Arkansas River (Pine Bluff Pool)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fd7c6ae8-71e7-4982-8d70-24a8ac71628f',
    'vocabulary_machine_name' => 'lake',
    'field_location' => array(
      'und' => array(
        0 => array(
          'geom' => NULL,
          'geo_type' => NULL,
          'lat' => NULL,
          'lon' => NULL,
          'left' => NULL,
          'top' => NULL,
          'right' => NULL,
          'bottom' => NULL,
          'geohash' => NULL,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
