<?php
/**
 * @file
 * fish_vocab_fish.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function fish_vocab_fish_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'bass',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '03719886-e9b4-4696-a880-04626b2b3bc7',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'white bass',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '567d5185-f7c3-434b-87a8-7876b7d7730c',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'trout',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5b236568-3d75-4d13-8582-74f922dcac62',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'striper',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7e646fd2-621d-4c12-b8e8-3262cc0e1746',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'crappie',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9d274b44-d7cf-4c72-beda-2b8226c85ca2',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'spotted bass',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a9549ad6-7748-43a3-92f7-a501bfdf2828',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'bream',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd07a8f6f-5394-4993-afc3-49107475b60c',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'smallmouth',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd7d1ca33-cd4e-400f-8229-f7ada24bf38c',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'catfish',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e9819ac4-295c-4c7a-9666-211fcf514493',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'walleye',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fa018f84-9bdc-432d-a5b2-0cc799cc2c9e',
    'vocabulary_machine_name' => 'fish_type',
    'url_alias' => array(),
  );
  return $terms;
}
